baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Hugo & Tailwind 3.0'
disableKinds = ["taxonomy","taxonomyTerm"]
summaryLength = 70

[[menu.main]]
  name = "Accueil"
  url = "/"

[[menu.main]]
  name = "A propos"
  url = "/nous"

[[menu.main]]
  name = "Projets"
  url = "/projets"

[[menu.main]]
  name = "Tutoriels"
  url = "/tutoriels"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.social]]
name = "GitHub"
url = "https://github.com/VotreCompteGithub"
pre = "<i class='fab fa-github'></i>"


[[menu.social]]
name = "Twitter"
url = "https://twitter.com/VotreCompteTwitter"
pre = "<i class='fab fa-twitter'></i>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



