baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Hugo & Tailwind 3.0'
disableKinds = ["taxonomy","taxonomyTerm"]
summaryLength = 70

[[menu.main]]
  identifier = 'Accueil'
  name = 'Accueil'
  title = 'page accueil'
  url = '/'
  weight = -115

[[menu.main]]
   identifier = 'nous'
  name = 'A propos'
  title = 'nous '
  url = '/nous'
  weight = -112

[[menu.main]]
  name = "Projets"
  url = "/projets"

[[menu.main]]
  name = "Tutoriels"
  url = "/tutoriels"

[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  title = 'blog section'
  url = '/blog/'
  weight = -110


[[menu.social]]
name = "GitHub"
url = "https://github.com/VotreCompteGithub"
pre = "<i class='fab fa-github'></i>"


[[menu.social]]
name = "Twitter"
url = "https://twitter.com/VotreCompteTwitter"
pre = "<i class='fab fa-twitter'></i>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



